# Generated by Django 5.2.17 on 2026-10-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_document',
            field=models.FileField(blank=True, upload_to='owner_kyc/%Y/%m'),
        ),
    ]
