# Generated by Django 5.2.17 on 2026-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
