# Generated by Django 5.2.17 on 2026-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicle_image_public_id_vehicle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_document',
            field=models.FileField(blank=True, upload_to='ids/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(db_index=True, default='requested', max_length=24),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='published', max_length=20),
        ),
    ]
