# Generated by Django 5.2.17 on 2026-10-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_direct_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity_status',
            field=models.CharField(default='not_submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
