# Generated by Django 5.2.17 on 2026-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_identity_status_user_identity_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
