# Generated by Django 5.2.17 on 2026-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_viewed_by_owner_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
