# Generated by Django 5.2.17 on 2026-10-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking_id_viewed_by_owner_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
