# Generated by Django 5.2.17 on 2026-10-04 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_legacy_cash_unverified(apps, schema_editor):
    Booking = apps.get_model('core', 'Booking')
    Booking.objects.filter(payment_status='paid_at_handover').update(payment_status='unverified_legacy')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hide_booked_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='renter_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_legacy_cash_unverified, migrations.RunPython.noop),
    ]
