# Generated by Django 5.2.17 on 2026-10-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_booking_cancellation_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receipt_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
