# Generated by Django 5.2.17 on 2026-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_privatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='renter_id_document',
            field=models.FileField(blank=True, upload_to='renter_ids/%Y/%m'),
        ),
        migrations.AddField(
            model_name='user',
            name='renter_id_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='renter_id_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
